import assert from 'node:assert/strict';
import {reconcileTradePosition} from '../src/services/portfolioTradeReplay';
import {calculatePortfolioResults} from '../src/services/portfolioResults';
import {comparePortfolioTransactions} from '../src/services/portfolioPerformance';
import type {Asset,PortfolioTransaction} from '../src/types/types';

const asset:Asset={id:'test',symbol:'TEST',name:'Synthetic',type:'stock',quantity:20,purchasePrice:150,purchaseDate:'2026-01-01',currency:'EUR',currentPrice:170};
const trade=(id:string,date:string,type:'buy'|'sell',quantity:number,price:number):PortfolioTransaction=>({id,date,type,quantity,price,total:quantity*price,createdAt:date+'T12:00:00Z',assetId:asset.id,assetSymbol:asset.symbol,assetName:asset.name,assetType:asset.type});
const buys=[trade('first','2026-01-01','buy',10,100),trade('second','2026-02-01','buy',10,200)];
const near=(actual:number,expected:number)=>assert.ok(Math.abs(actual-expected)<1e-8,`${actual} != ${expected}`);
const sale=trade('retro-sale','2026-01-15','sell',5,120);
const unrelated={...asset,id:'other',symbol:'OTHER'};
const result=reconcileTradePosition([asset,unrelated],[{...asset,quantity:15},unrelated],[sale,...buys],sale);
near(result[0].purchasePrice,2500/15);assert.equal(result[0].quantity,15);
assert.equal(result[0].currentPrice,170);assert.equal(result[1],unrelated,'Other assets, their order and quotes remain unchanged');
const profit=calculatePortfolioResults(result,[sale,...buys]);
near(profit.realizedGain,100);near(profit.unrealizedGain,50+400);near(profit.totalGain,150+400);
// A backdated purchase also changes the cost assigned to a later sale.
const laterSale=trade('later-sale','2026-02-01','sell',5,150);
const old={...asset,quantity:5,purchasePrice:100};
const purchase=trade('retro-buy','2026-01-15','buy',5,200);
const purchased=reconcileTradePosition([old],[{...old,quantity:10,purchasePrice:150}], [purchase,buys[0],laterSale],purchase);
near(purchased[0].purchasePrice,2000/15);near(calculatePortfolioResults(purchased,[purchase,buys[0],laterSale]).realizedGain,250/3);
// The final current quantity alone does not prove ownership on the sale date.
const earlySale=trade('too-early','2025-12-31','sell',5,120);
assert.throws(()=>reconcileTradePosition([asset],[{...asset,quantity:15}],[earlySale,...buys],earlySale),/suficientes unidades/);
const excessive=trade('too-many','2026-01-15','sell',11,120);
assert.throws(()=>reconcileTradePosition([asset],[{...asset,quantity:9}],[excessive,...buys],excessive),/suficientes unidades/);
const manual:PortfolioTransaction={...buys[0],id:'manual',type:'edit'};
assert.throws(()=>reconcileTradePosition([asset],[{...asset,quantity:15}],[sale,...buys,manual],sale),/correcciones manuales/);
assert.throws(()=>reconcileTradePosition([asset],[{...asset,quantity:15}],[sale,buys[1]],sale),/coste inicial/);
const forward=trade('forward','2026-03-01','sell',5,120);
assert.equal(reconcileTradePosition([asset],result,[forward,manual,...buys],forward),result,'Forward-only legacy corrections retain their explicit current basis');
const closedSale=trade('close','2026-03-01','sell',20,160);
assert.deepEqual(reconcileTradePosition([asset],[],[...buys,closedSale],closedSale),[]);
near(calculatePortfolioResults([], [...buys,closedSale]).realizedGain,200);
const firstOpening={...buys[0],id:'position-test',provenance:'initial-position' as const};
const first={...asset,quantity:10,purchasePrice:100};
near(reconcileTradePosition([first],[{...first,quantity:5}],[sale,firstOpening],sale)[0].purchasePrice,100);
const fractionBuys=[trade('f1','2026-01-01','buy',.1,100),trade('f2','2026-02-01','buy',.2,200)];
const fractions={...asset,quantity:.3,purchasePrice:500/3};
const fractionSale=trade('fraction-close','2026-03-01','sell',.3,200);
assert.deepEqual(reconcileTradePosition([fractions],[],[...fractionBuys,fractionSale],fractionSale),[],'Floating-point dust must not leave a zero-quantity open position');
const tied=buys.map(t=>({...t,date:'2026-01-01',createdAt:'2026-01-01T12:00:00Z'}));
const sameDay={...sale,date:'2026-01-01',createdAt:'2026-01-01T13:00:00Z'};
near(reconcileTradePosition([asset],[{...asset,quantity:15}],[sameDay,...tied],sameDay)[0].purchasePrice,150);
const keys=['z','A','a','a-b','ab','\uE000','\u{10000}'];
assert.deepEqual(keys.map(id=>({...firstOpening,id})).sort(comparePortfolioTransactions).map(t=>t.id),['A','a','a-b','ab','z','\uE000','\u{10000}']);
console.log('Trade replay passed: retroactive sales/buys, average cost and realized results, opening basis, ownership at each sale, unknown/corrected ledgers, full closures, precision and unrelated positions.');
