import assert from 'node:assert/strict';
import {portfolioPositionGroups} from '../src/services/portfolioPositionGroups';
import {assetValue} from '../src/services/assetValuation';
import type {Asset} from '../src/types/types';
const now=Date.parse('2026-10-08T12:00:00Z');
const base:Asset={id:'a',symbol:'NXTE.XD',name:'Nextil',isin:'ES0126962069',type:'stock',quantity:100,purchasePrice:.8,purchaseDate:'2026-01-01',currency:'EUR',currentPrice:1.1,previousClose:1,quotedAt:'2026-10-08T11:30:00Z'};
const lots=[base,{...base,id:'b',quantity:200,purchasePrice:.9,purchaseDate:'2026-03-01'},{...base,id:'c',purchasePrice:1,purchaseDate:'2026-05-01'}];
const original=structuredClone(lots);
const group=portfolioPositionGroups(lots,now)[0];
const near=(actual:number,expected:number)=>assert.ok(Math.abs(actual-expected)<1e-8,`${actual} != ${expected}`);
assert.equal(group.asset.quantity,400);near(group.asset.purchasePrice,.9);
near(group.currentValue,440);near(group.investedValue,360);near(group.currentValue-group.investedValue,80);
near(group.latestChange,40);near(group.latestChangePercent,10);
assert.equal(group.isToday,true);assert.equal(group.lots.length,3);assert.equal(group.estimatedCount,0);
assert.deepEqual(lots,original,'Grouping must never rewrite positions or their purchase basis');
const reversed=portfolioPositionGroups([...lots].reverse(),now)[0];assert.equal(group.asset.id,reversed.asset.id);near(reversed.asset.purchasePrice,.9);
const partial=portfolioPositionGroups([{...base,currentPrice:undefined},...lots.slice(1)],now)[0];
near(partial.currentValue,410);assert.equal(partial.estimatedCount,1);assert.ok(Number.isNaN(partial.latestChangePercent));
const dates=portfolioPositionGroups([base,{...lots[1],quotedAt:'2026-10-07T11:30:00Z'}],now)[0];
assert.ok(dates.mixedDates);assert.ok(Number.isNaN(dates.latestChangePercent),'Do not combine different closing dates into daily return');
assert.equal(portfolioPositionGroups([base,{...base,id:'other',symbol:'B02.F'}],now).length,2,'Keep distinct trading listings');
assert.equal(portfolioPositionGroups([base,{...base,id:'other',currency:'USD'}],now).length,2,'Keep different cost currencies');
assert.equal(portfolioPositionGroups([base,{...base,id:'other',type:'fund'}],now).length,2);
assert.equal(portfolioPositionGroups([base,{...base,id:'other',isin:'ES0000000001'}],now).length,2,'Contradictory ISINs cannot merge');
assert.equal(portfolioPositionGroups([base,{...base,id:'other',isin:undefined}],now).length,1,'An unambiguous symbol can inherit the known ISIN');
assert.equal(portfolioPositionGroups([base,{...base,id:'other',isin:'ES0000000001'},{...base,id:'unknown',isin:undefined}],now).length,3);
const funds=[{...base,type:'fund' as const,symbol:'Class A'},{...base,id:'other',type:'fund' as const,symbol:'Another label'}];
assert.equal(portfolioPositionGroups(funds,now).length,1,'Same fund class ISIN groups despite labels');
const all=[...lots,{...base,id:'crypto-a',symbol:'BTC-EUR',isin:undefined,type:'crypto' as const,quantity:.01,purchasePrice:40000,currentPrice:50000},{...base,id:'crypto-b',symbol:'BTC-EUR',isin:undefined,type:'crypto' as const,quantity:.02,purchasePrice:45000,currentPrice:50000}];
near(portfolioPositionGroups(all,now).reduce((sum,g)=>sum+g.currentValue,0),all.reduce((sum,a)=>sum+assetValue(a),0));
assert.ok(portfolioPositionGroups(all,now).filter(g=>g.lots.length>1).every(g=>!all.some(a=>a.id===g.asset.id)));
console.log('PASS: weighted basis, summed valuations, exact identities/classes/listings, fractional crypto, estimated/mixed dates, stable display IDs and unchanged original records.');
