import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { portfolioQuoteStatus, quoteDateLabel } from '../src/services/portfolioQuoteStatus';
import { createQuoteSnapshot } from '../src/services/portfolioPerformance';
import { buildConsolidatedPortfolioExposures, resolveLiveUnderlyingSelection } from '../src/services/portfolioComposition';
import type { Asset } from '../src/types/types';

const now = Date.parse('2026-10-01T12:00:00Z');
const asset: Asset = { id: 'test', symbol: 'TEST', name: 'Synthetic fund', type: 'fund', quantity: 10, purchasePrice: 8, currentPrice: 10, currency: 'EUR', purchaseDate: '2026-01-01', lastCheckedAt: new Date(now).toISOString(), quotedAt: '2026-09-30T12:00:00Z' };
assert.equal(portfolioQuoteStatus(asset, now).blockers.length, 0);
assert.ok(createQuoteSnapshot([asset], [], new Date(now).toISOString()));
const missing = { ...asset, id: 'missing', currentPrice: undefined };
assert.deepEqual(portfolioQuoteStatus(missing, now).blockers, ['sin cotización válida en euros']);
assert.equal(createQuoteSnapshot([asset, missing], [], new Date(now).toISOString()), null);
const oldQuote = { ...asset, quotedAt: '2026-09-20T12:00:00Z' };
assert.ok(portfolioQuoteStatus(oldQuote, now).recentlyChecked);
assert.ok(portfolioQuoteStatus(oldQuote, now).stalePrice);
assert.equal(createQuoteSnapshot([oldQuote], [], new Date(now).toISOString()), null, 'An old NAV cannot create a verified valuation after a recent check');
assert.equal(portfolioQuoteStatus({ ...asset, quotedAt: '2026-09-27T12:00:00Z' }, now).stalePrice, false);
assert.equal(portfolioQuoteStatus({ ...asset, type: 'stock', quotedAt: '2026-09-28T12:00:00Z' }, now).stalePrice, false);
assert.equal(portfolioQuoteStatus({ ...asset, type: 'crypto', quotedAt: '2026-09-28T12:00:00Z' }, now).stalePrice, true);
assert.equal(portfolioQuoteStatus({ ...asset, lastCheckedAt: '2026-10-02T12:00:00Z' }, now).recentlyChecked, false);
assert.equal(portfolioQuoteStatus({ ...asset, lastCheckedAt: '2026-09-30T12:00:00Z' }, now).blockers.length, 1);
assert.equal(portfolioQuoteStatus({ ...asset, lastCheckedAt: undefined }, now).recentlyChecked, false);
assert.equal(portfolioQuoteStatus({ ...asset, quotedAt: undefined }, now).unknownPriceDate, true);
assert.equal(quoteDateLabel('bad date'), 'No disponible');
assert.equal(portfolioQuoteStatus({ ...missing, currentPrice: 0 }, now).blockers.length, 0);
assert.equal(portfolioQuoteStatus({ ...asset, type: 'cash', lastCheckedAt: undefined, quotedAt: undefined }, now).blockers.length, 0);
const holding = { symbol: 'EXAMPLE', name: 'Example company', percentage: 50 };
const positions = [{ ...asset, holdings: [holding] }, { ...asset, id: 'second', holdings: [holding] }];
const exposures = buildConsolidatedPortfolioExposures(positions);
const selection = { holding, parentAsset: positions[0], exposure: exposures.find(e => !e.isResidual)! };
assert.equal(selection.exposure.value, 100);
const refreshed = positions.map((a, i) => ({ ...a, currentPrice: i ? 20 : 30 }));
const refreshedExposures = buildConsolidatedPortfolioExposures(refreshed);
const resolved = resolveLiveUnderlyingSelection(selection, refreshed, refreshedExposures)!;
assert.equal(resolved.exposure!.value, 250);
assert.equal(resolved.exposure!.weight, 50);
assert.equal(resolved.parentAsset.currentPrice, 30);
assert.equal(resolveLiveUnderlyingSelection(resolved, refreshed, refreshedExposures), resolved);
assert.equal(resolveLiveUnderlyingSelection(selection, [], []), null);
assert.equal(resolveLiveUnderlyingSelection(selection, refreshed, []), null);
const service = readFileSync(new URL('../src/services/newsService.ts', import.meta.url), 'utf8');
assert.match(service, /import type \{[\s\S]*?\} from '@supabase\/supabase-js'/);
assert.match(service, /return getAppSupabaseClient\(\)/);
const sharedClient = readFileSync(new URL('../src/services/supabaseClient.ts', import.meta.url), 'utf8');
assert.match(sharedClient, /clientPromise \?\?= import\('@supabase\/supabase-js'\)/);
assert.match(sharedClient, /storageKey: 'freewallet-news-auth'/);
assert.doesNotMatch(service, /createClient\(/, 'Noticias must not create a second Auth client');
assert.doesNotMatch(service, /const client = requireClient\(\)/);
console.log('Dashboard follow-ups passed: current consolidated detail, deleted selections, snapshot blockers, consultation/price dates, delayed NAV margins, zero prices and on-demand editorial SDK.');
