import assert from 'node:assert/strict';
import { parseGoogleFinanceQuote,parseCoinGeckoQuote,cryptoCoinId } from '../src/services/market/alternativeQuotes';
import { googleListing,stockQuoteMarkets } from '../src/services/market/stockQuoteMarkets';
import { priceRefreshInterval } from '../src/services/market/priceRefreshPolicy';
import type { Asset } from '../src/types/types';

const now=Date.parse('2026-10-08T11:35:00Z'),at=now/1000-30;
const record=['/g/fixture',['NXT','BME'],'Nueva Expresion Textil SA',0,'EUR',[1.038,-.008,0],null,1.046,null,'ES',null,[at]];
const html=(value:unknown)=>`<script>AF_initDataCallback({key: 'ds:8', hash: '1', data:${JSON.stringify([value])}, sideChannel: {}});</script>`;
const quote=parseGoogleFinanceQuote(html(record),'NXT:BME',now)!;
assert.equal(quote.price,1.038);assert.equal(quote.previousClose,1.046);
assert.equal(quote.quotedAt,new Date(at*1000).toISOString());
assert.equal(quote.source,'Google Finance');
assert.equal(parseGoogleFinanceQuote(html(record),'NXT:FRA',now),null,'Different venue is never accepted');
assert.equal(parseGoogleFinanceQuote(html(record),'NXTE:BME',now),null,'Similar ticker is not the same listing');
assert.equal(parseGoogleFinanceQuote(html([...record.slice(0,11),[now/1000+600]]),'NXT:BME',now),null);
assert.equal(parseGoogleFinanceQuote('<script>alert(1)</script>','NXT:BME',now),null);
const crypto=parseCoinGeckoQuote({bitcoin:{eur:55000,last_updated_at:at,eur_24h_change:42}},'BTC-USD',now)!;
assert.equal(crypto.price,55000);assert.equal(crypto.currency,'EUR');assert.equal(crypto.symbol,'BTC-EUR');
assert.ok(Number.isNaN(crypto.previousClose),'A rolling 24h change must not masquerade as a UTC daily close');
assert.equal(parseCoinGeckoQuote({bitcoin:{eur:55000,last_updated_at:at}},'ROSE-EUR',now),null);
assert.equal(parseCoinGeckoQuote({bitcoin:{eur:55000}},'BTC-EUR',now),null);
assert.equal(cryptoCoinId('ROSE-USD'),'oasis-network');assert.equal(cryptoCoinId('UNKNOWN-EUR'),undefined);
assert.equal(googleListing('AMP.MC'),'AMP:BME');assert.equal(googleListing('OHLA.MC'),'OHLA:BME');
assert.equal(googleListing('AAPL','NMS'),'AAPL:NASDAQ');assert.equal(googleListing('AAPL'),undefined,'Unknown venue cannot be guessed');
assert.equal(googleListing('IBM','NYQ'),'IBM:NYSE');assert.equal(googleListing('SAP.DE'),'SAP:ETR');
const nextil:Asset={id:'n',symbol:'NXTE.XD',name:'Nextil',isin:'ES0126962069',type:'stock',quantity:10,purchasePrice:1,purchaseDate:'2026-01-01',currency:'EUR'};
assert.equal(stockQuoteMarkets(nextil)[1].google,'NXT:BME');
assert.equal(stockQuoteMarkets({...nextil,isin:'ES0000000000'}).length,1,'Conflicting ISIN prevents the verified alias');
assert.equal(priceRefreshInterval(nextil,true,now),60000);
assert.equal(priceRefreshInterval(nextil,false,now),300000);
assert.equal(priceRefreshInterval(nextil,true,Date.parse('2026-10-11T11:00:00Z')),300000);
assert.equal(priceRefreshInterval({...nextil,type:'crypto'},true,Date.parse('2026-10-11T01:00:00Z')),60000,'Crypto is active on weekends and overnight');
assert.equal(priceRefreshInterval({...nextil,type:'fund'},true,now),300000);
assert.equal(priceRefreshInterval({...nextil,symbol:'AAPL'},true,now),300000,'US market is not open during the Spanish morning');
console.log('PASS: exact ticker/venue/currency, actual provider timestamps, missing/invalid observations, general exchange mapping, crypto identity and visible-dashboard session polling.');
