import assert from 'node:assert/strict';
import { createTimingGame, generateTimingPrices, timingOrderAvailable, timingReducer, timingScore, timingValue, TIMING_RULES, type TimingGame, type TimingRoundResult } from '../src/components/academy/simulators/marketTimingEngine';

const near = (actual: number, expected: number, message?: string) => assert.ok(Math.abs(actual - expected) < 1e-7, message || `${actual} != ${expected}`);
const start = (seed = 1) => timingReducer(createTimingGame(), { type: 'start', seed });
const step = (game: TimingGame, ticks = 1): TimingGame => ticks ? step(timingReducer(game, { type: 'tick' }), ticks - 1) : game;
const flat = (): TimingGame => ({ ...start(), path: Array.from({ length: TIMING_RULES.ticks + 1 }, () => 100) });
const initial = createTimingGame();
near(timingValue(initial.player, 100), 10000);
near(timingValue(initial.dca, 100), 10000);
assert.deepEqual(generateTimingPrices(42), generateTimingPrices(42));
assert.notDeepEqual(generateTimingPrices(42), generateTimingPrices(43));
for (let seed = 0; seed < 200; seed++) {
    const prices = generateTimingPrices(seed);
    assert.equal(prices.length, 76);
    assert.equal(prices[0], 100);
    assert.ok(prices.every(price => Number.isFinite(price) && price > 0));
}
let game = flat();
near(game.dca.cash, 9000);
near(game.dca.fees, 1.5);
near(timingValue(game.dca, 100), 9000 + 998.5 / 1.001);
assert.ok(timingValue(game.dca, 100) > 9900, 'Uninvested DCA cash counts from the first tick');
assert.deepEqual(game.history, [{ tick: 0, price: 100 }], 'Chart cannot expose future prices');
game = timingReducer(game, { type: 'order', side: 'buy', fraction: 0.5 });
assert.equal(timingOrderAvailable(game, 'buy'), false);
near(game.player.cash, 10000);
assert.equal(timingReducer(game, { type: 'order', side: 'buy', fraction: 1 }), game, 'Repeated clicks cannot queue duplicate orders');
game = step(game);
near(game.player.cash, 10000);
const paused = timingReducer(game, { type: 'pause' });
assert.equal(step(paused, 20), paused);
assert.equal(timingReducer(paused, { type: 'order', side: 'buy', fraction: 1 }), paused);
game = step(timingReducer(paused, { type: 'resume' }));
near(game.player.cash, 5000);
near(game.player.shares, 4992.5 / 100.1);
near(game.player.fees, 7.5);
assert.equal(game.trades[0].tick, 2);
assert.equal(timingOrderAvailable(game, 'sell'), false, 'Execution starts a cooldown');
game = step(game, 4);
assert.equal(timingOrderAvailable(game, 'sell'), true);
game = step(timingReducer(game, { type: 'order', side: 'sell', fraction: 0.5 }), 2);
near(game.player.shares, 4992.5 / 100.1 / 2);
const gross = (4992.5 / 100.1 / 2) * 99.9;
near(game.player.cash, 5000 + gross * 0.9985);
near(game.player.fees, 7.5 + gross * 0.0015);
const delayed: TimingGame = { ...flat(), path: Array.from({ length: 76 }, (_, index) => index === 2 ? 200 : 100) };
const filled = step(timingReducer(delayed, { type: 'order', side: 'buy', fraction: 1 }), 2);
near(filled.player.shares, 9985 / 200.2, 'Orders execute at the future quote, not the click price');
let capped = flat();
while (capped.phase === 'running' && capped.tick < 65) {
    if (timingOrderAvailable(capped, capped.player.cash >= 1 ? 'buy' : 'sell')) {
        capped = timingReducer(capped, { type: 'order', side: capped.player.cash >= 1 ? 'buy' : 'sell', fraction: 1 });
    }
    capped = step(capped);
}
assert.equal(capped.trades.length, 8);
assert.equal(timingOrderAvailable(capped, 'buy'), false);
assert.equal(timingOrderAvailable(capped, 'sell'), false);
const finalFlat = step(flat(), 75);
near(finalFlat.dca.cash, 0);
near(finalFlat.dca.fees, 15);
near(timingValue(finalFlat.dca, 100), 9985 / 1.001);
assert.equal(finalFlat.phase, 'round-result');
assert.equal(finalFlat.history.length, 76);
assert.equal(finalFlat.results.length, 1);
assert.equal(step(finalFlat, 10), finalFlat, 'A completed round cannot accrue more trades or DCA buys');
const second = timingReducer(finalFlat, { type: 'next' });
assert.equal(second.round, 2);
assert.equal(second.tick, 0);
near(second.player.cash, 10000);
assert.equal(second.trades.length, 0);
assert.equal(second.results.length, 1);
assert.notDeepEqual(second.path, finalFlat.path);
const third = timingReducer(step(second, 75), { type: 'next' });
const finished = step(third, 75);
assert.equal(finished.phase, 'finished');
assert.equal(finished.results.length, 3);
assert.equal(timingReducer(finished, { type: 'next' }), finished);
assert.equal(timingReducer(finished, { type: 'start', seed: 2 }).results.length, 0);
const late = step(flat(), 74);
assert.equal(timingOrderAvailable(late, 'buy'), false, 'Too-late orders cannot disappear at the finish');
const bought = step(timingReducer(flat(), { type: 'order', side: 'buy', fraction: 1 }), 2);
const crash = step({ ...bought, path: bought.path.map((price, index) => index >= 3 ? 50 : price) });
assert.ok(crash.drawdown > 50 && crash.drawdown < 51);
const result = (edge: number): TimingRoundResult => ({ round: 1, playerValue: 10000 + edge, dcaValue: 10000, edge, trades: 1, fees: 1, dcaFees: 1, drawdown: 0 });
assert.equal(timingScore([result(1000)]).won, false);
assert.equal(timingScore([result(50), result(50), result(-1)]).won, false);
assert.equal(timingScore([result(100), result(50), result(-40)]).won, true);
assert.equal(timingScore([result(1000), result(-20), result(-20)]).won, false, 'One lucky round is insufficient');
console.log('Market timing passed: fair cash-inclusive DCA, identical costs, delayed/partial execution, cooldown, order cap, immutable rounds, hidden future, pause, risk and three-round scoring.');
