import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import {normalizeFundamentals,formatFundamentalMoney} from '../src/services/market/fundamentals';
import { PGlite } from '@electric-sql/pglite';
import { quoteCurrency, datedFx, marketSymbolMatches } from '../supabase/functions/_shared/quoteCurrency';
import { fetchMarketPrice, providerJson, parseFund, parseChart } from '../supabase/functions/daily-market-data/providers';

assert.deepEqual(quoteCurrency('GBp'),{currency:'GBP',scale:0.01});
assert.ok(marketSymbolMatches('USDEUR=X','EUR=X','EUR'));
assert.equal(marketSymbolMatches('USDEUR=X','GBP=X','GBP'),false);
assert.equal(marketSymbolMatches('VOD.L','VOD','USD'),false);
assert.deepEqual(quoteCurrency('GBP'),{currency:'GBP',scale:1});
assert.throws(()=>quoteCurrency('UNKNOWN'));
assert.equal(datedFx([{at:'2026-10-02T00:00:00Z',close:1.1},{at:'2026-10-07T00:00:00Z',close:1.2}],'2026-10-05T12:00:00Z').close,1.1);
assert.throws(()=>parseFund({data:{entity:{isin:'WRONG',lastQuote:{price:4,datetime:'2026-10-01'},currency:{code:'EUR'},classes:[{isin:'IE00BYX5NX33'}]}}},'IE00BYX5NX33'),'Do not borrow another class NAV');
assert.throws(()=>parseChart({chart:{result:[{meta:{symbol:'OTHER',currency:'EUR'}}]}},'VOD.L'));
const fundamentals=normalizeFundamentals({quoteSummary:{result:[{price:{symbol:'VOD.L',currency:'GBp',marketCap:{raw:1000000}},defaultKeyStatistics:{trailingEps:{raw:8}},summaryDetail:{dividendRate:{raw:4},fiftyTwoWeekHigh:{raw:150}},financialData:{financialCurrency:'GBP',ebitda:{raw:900000}}}]}},'VOD.L');
assert.equal(fundamentals.marketCapCurrency,'GBP');assert.equal(fundamentals.financialCurrency,'GBP');
assert.equal(formatFundamentalMoney(fundamentals.eps,fundamentals.epsCurrency),'0,08 GBP');
assert.equal(formatFundamentalMoney(fundamentals.dividendRate,fundamentals.dividendCurrency),'0,04 GBP');
assert.equal(formatFundamentalMoney(fundamentals.ebitda,fundamentals.financialCurrency),'900.000 GBP');
const realFetch=globalThis.fetch;
try {
    const day=Math.floor(Date.parse('2026-10-06T10:00:00Z')/1000), previous=day-86400;
    const requested:string[]=[];
    globalThis.fetch=(async(url)=>{
        const target=String(url);requested.push(target);
        const symbol=decodeURIComponent(target.split('/chart/')[1].split('?')[0]);
        const fx=symbol==='GBPEUR=X';
        return Response.json({chart:{result:[{meta:{symbol,currency:fx?'EUR':'GBp',regularMarketPrice:127.75,regularMarketTime:day,previousClose:120},
            timestamp:[previous,day],indicators:{quote:[{close:fx?[1.1,1.2]:[120,127.75]}]}}]}});
    }) as typeof fetch;
    const quote=await fetchMarketPrice({instrument:'VOD.L',symbol:'VOD.L',type:'stock',isin:'GB00BH4HKS39'},'fixture');
    assert.equal(quote.price_eur,1.2775*1.2);assert.equal(quote.original_unit,'GBp');assert.equal(quote.original_currency,'GBP');
    assert.equal(quote.previous_close_eur,1.2*1.1);
    assert.ok(requested.every(url=>!url.includes('finect')),'A stock ISIN must not route to the fund provider');
    let attempts=0;globalThis.fetch=(async()=>++attempts===1 ? new Response('',{status:429}) : Response.json({ok:true})) as typeof fetch;
    assert.deepEqual(await providerJson('https://fixture.invalid'),{ok:true});assert.equal(attempts,2);
    const aborted=new AbortController();aborted.abort();await assert.rejects(providerJson('https://fixture.invalid',aborted.signal));
} finally {globalThis.fetch=realFetch;}

const db=new PGlite();
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',T='44444444-4444-4444-8444-444444444444';
const migration=(suffix:string)=>readFileSync(`supabase/migrations/${readdirSync('supabase/migrations').find(n=>n.endsWith(suffix))}`,'utf8');
const login=async(uid:string,sid:string,aal='aal1')=>db.exec(`reset role;select set_config('request.jwt.claim.sub','${uid}',false);select set_config('request.jwt.claims','{"session_id":"${sid}","aal":"${aal}"}',false);set role authenticated;`);
try {
    await db.exec(`create role anon;create role authenticated;create role service_role;
        create schema auth;create schema vault;create schema cron;create schema net;create schema storage;
        create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz default now(),is_anonymous boolean default false);
        create table auth.sessions(id uuid primary key,user_id uuid);create table auth.mfa_factors(id uuid,user_id uuid,status text);
        create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
        create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
        create table vault.decrypted_secrets(name text,decrypted_secret text);insert into vault.decrypted_secrets values('daily_market_job_secret','fixture');
        create function cron.schedule(text,text,text) returns bigint language sql as $$select 1::bigint$$;
        create table net._http_response(id bigint,timed_out boolean,status_code integer,error_msg text);
        create table storage.buckets(id text primary key,name text,public boolean);create table storage.objects(id uuid,bucket_id text,owner_id text);alter table storage.objects enable row level security;
        grant usage on schema auth,public,storage to authenticated,anon,service_role;
        insert into auth.users(id,email) values('${A}','daniel230401@gmail.com'),('${B}','editor@example.test');insert into auth.sessions values('${S}','${A}'),('${T}','${B}');`);
    for(const name of ['portfolio_foundation.sql','portfolio_commands.sql','portfolio_mfa_guard.sql','portfolio_command_validation.sql','portfolio_opening_basis.sql','daily_market_data.sql','daily_market_accounting_calendar.sql']) await db.exec(migration(name));
    await db.exec(readFileSync('supabase/news-schema.sql','utf8').replace('create extension if not exists pgcrypto;',''));
    for(const name of ['architecture_hardening.sql','market_publication_hardening.sql','portfolio_delta_commands.sql','architecture_advisor_cleanup.sql']) await db.exec(migration(name));
    await login(A,S);
    assert.equal((await db.query<{v:boolean}>('select public.ensure_news_owner() v')).rows[0].v,true);
    const asset={id:'vod',symbol:'VOD.L',isin:'GB00BH4HKS39',name:'Vodafone',type:'stock',quantity:2,purchasePrice:1,purchaseDate:'2026-01-01',currency:'EUR'};
    const opening={id:'initial-buy',assetId:'vod',assetSymbol:'VOD.L',assetName:'Vodafone',assetType:'stock',type:'buy',quantity:2,price:1,total:2,date:'2026-01-01',createdAt:'2026-01-01T12:00:00Z',provenance:'trade'};
    const book={freewallet_portfolio_v1:JSON.stringify({version:1,assets:[asset],transactions:[opening]}),freewallet_portfolio_csv_holdings_raw:'large-fixture'};
    const imported=await db.query<{r:{revision:number}}>("select public.commit_portfolio(-1,gen_random_uuid(),'import',$1) r",[JSON.stringify(book)]);
    const revision=imported.rows[0].r.revision;
    const id=crypto.randomUUID();
    const patched=await db.query<{r:{revision:number,data:object,patch:boolean}}>('select public.patch_portfolio($1,$2,$3) r',[revision,id,JSON.stringify({freewallet_theme_mode:'light'})]);
    assert.equal(patched.rows[0].r.patch,true);assert.deepEqual(patched.rows[0].r.data,{freewallet_theme_mode:'light'});
    await db.query('select public.patch_portfolio($1,$2,$3)',[revision,id,JSON.stringify({freewallet_theme_mode:'light'})]);
    await assert.rejects(db.query('select public.patch_portfolio($1,$2,$3)',[revision,id,JSON.stringify({freewallet_theme_mode:'dark'})]));
    await assert.rejects(db.query('select public.patch_portfolio($1,gen_random_uuid(),$2)',[revision,JSON.stringify({freewallet_theme_mode:'dark'})]));
    await assert.rejects(db.query('select public.patch_portfolio($1,gen_random_uuid(),$2)',[revision+1,JSON.stringify({freewallet_settings:'[]'})]));
    await assert.rejects(db.query('select public.patch_portfolio($1,gen_random_uuid(),$2)',[revision+1,JSON.stringify({private_key:'secret'})]));
    await db.query('select public.patch_portfolio($1,gen_random_uuid(),$2,$3)',[revision+1,'{}',['freewallet_portfolio_csv_holdings_raw']]);
    const invitation=await db.query<{r:{deliveryRequired:boolean}}>("select public.prepare_news_invitation('editor@example.test') r");
    assert.equal(invitation.rows[0].r.deliveryRequired,false,'Existing Auth account recovers membership without mailing');
    const prepared=(await db.query<{r:{id:string,deliveryRequired:boolean}}>("select public.prepare_news_invitation('new@example.test') r")).rows[0].r;
    assert.equal(prepared.deliveryRequired,true);
    const retry=(await db.query<{r:{id:string,deliveryRequired:boolean}}>("select public.prepare_news_invitation('new@example.test') r")).rows[0].r;
    assert.equal(retry.id,prepared.id);assert.equal(retry.deliveryRequired,false,'In-flight invitation cannot mail twice');
    await db.exec(`reset role;insert into auth.users(id,email) values(gen_random_uuid(),'new@example.test');`);
    assert.equal((await db.query<{v:boolean}>('select public.complete_news_invitation($1,true) v',[prepared.id])).rows[0].v,true,'Recover after Auth registered the account but response was lost');
    await login(B,T);assert.equal((await db.query<{v:boolean}>('select public.has_pending_news_invitation() v')).rows[0].v,true);
    assert.equal((await db.query<{v:boolean}>('select public.accept_news_editor_invitation() v')).rows[0].v,true);
    await db.query("insert into public.news_posts(slug,title,author_id) values('editor-article','Fixture',$1)",[B]);
    await login(A,S);await db.query("insert into public.news_posts(slug,title,author_id,status) values('owner-article','Fixture',$1,'published')",[A]);
    await login(B,T);
    assert.equal((await db.query("update public.news_posts set title='Unauthorized' where slug='owner-article' returning id")).rows.length,0);
    assert.equal((await db.query("update public.news_posts set title='Own edit' where slug='editor-article' returning id")).rows.length,1);
    await db.exec(`reset role;insert into auth.mfa_factors values(gen_random_uuid(),'${B}','verified');set role authenticated;`);
    assert.equal((await db.query<{v:boolean}>('select public.is_news_admin() v')).rows[0].v,false);
    assert.equal((await db.query("update public.news_posts set title='No MFA' where slug='editor-article' returning id")).rows.length,0);
    await login(B,T,'aal2');assert.equal((await db.query<{v:boolean}>('select public.is_news_admin() v')).rows[0].v,true);
    await db.exec(`reset role;delete from auth.sessions where id='${T}';set role authenticated;`);
    assert.equal((await db.query<{v:boolean}>('select public.is_news_admin() v')).rows[0].v,false);
    await db.exec('reset role;set role anon;');
    await assert.rejects(db.query('select public.is_news_admin()'));
    assert.equal((await db.query('select slug from public.news_posts')).rows.length,1,'Public published article remains readable');
    await db.exec('reset role;');
    const run=(await db.query<{r:{id:string,instrumentsV2:Array<{instrument:string,type:string}>}}>("select public.begin_daily_market_refresh('fixture') r")).rows[0].r;
    assert.ok(run.instrumentsV2.some(i=>i.instrument==='VOD.L'&&i.type==='stock'));
    const now=new Date().toISOString(), price={instrument:'VOD.L',quoted_at:now,checked_at:now,price_eur:1.5,previous_close_eur:1.4,original_price:125,original_currency:'GBP',original_unit:'GBp',unit_scale:0.01,fx_rate:1.2,fx_at:now,source:'Yahoo Finance'};
    await db.query('select public.finish_daily_market_refresh($1,$2,$3)',[run.id,JSON.stringify([price]),'[]']);
    assert.equal((await db.query<{n:number}>('select count(*)::int n from portfolio_private.daily_snapshots')).rows[0].n,0,'Publication does not capture or lock all portfolios');
    assert.equal((await db.query<{v:string}>('select public.capture_market_snapshot($1,$2) v',[run.id,A])).rows[0].v,'captured');
    const snapshots=(await db.query<{transactions:unknown[],valuation_kind:string}>('select transactions,valuation_kind from portfolio_private.daily_snapshots')).rows;
    assert.deepEqual(snapshots[0].transactions,[]);assert.equal(snapshots[0].valuation_kind,'mixed-observations');
    await login(A,S);
    const daily=(await db.query<{r:{snapshots:Array<{ledgerVersion:number}>,ledger:unknown[],prices:Array<{original_unit:string}>}}>('select public.read_daily_market_data_v2() r')).rows[0].r;
    assert.equal(daily.snapshots.length,1);assert.equal(daily.prices[0].original_unit,'GBp');
    const legacy=(await db.query<{r:{snapshots:Array<{transactions:unknown[]}>}}>('select public.read_daily_market_data() r')).rows[0].r;
    assert.equal(legacy.snapshots.length,1);
    await db.exec('reset role;');
    const firstVersion=(await db.query<{v:number}>('select ledger_version v from portfolio_private.daily_snapshots')).rows[0].v;
    await db.exec("update portfolio_private.daily_snapshots set snapshot_date=snapshot_date-1;");
    await login(A,S);
    const changed={version:1,assets:[{...asset,quantity:3,purchasePrice:1.333333333333}],transactions:[opening,{...opening,id:'backdated-buy',quantity:1,price:2,total:2,date:'2026-01-02',createdAt:new Date().toISOString()}]};
    await db.query('select public.patch_portfolio($1,gen_random_uuid(),$2)',[revision+2,JSON.stringify({freewallet_portfolio_v1:JSON.stringify(changed)})]);
    await assert.rejects(db.query('select public.patch_portfolio($1,gen_random_uuid(),$2)',[revision+3,JSON.stringify({freewallet_portfolio_v1:JSON.stringify({...changed,transactions:[]})})]));
    await db.exec('reset role;');
    assert.equal((await db.query<{v:string}>('select public.capture_market_snapshot($1,$2) v',[run.id,A])).rows[0].v,'captured');
    assert.equal((await db.query<{n:number}>('select count(*)::int n from portfolio_private.snapshot_ledger')).rows[0].n,2,'Operations are stored once across valuations');
    assert.equal((await db.query<{n:number}>('select count(*)::int n from portfolio_private.snapshot_ledger where entry_no<=$1',[firstVersion])).rows[0].n,1,'A later backdated trade cannot enter the old snapshot book');
    await login(B,T,'aal2');
    await assert.rejects(db.query('select public.read_daily_market_data_v2()'),'Revoked B session cannot read A ledger');
    await db.exec('reset role;');
    const failedRun=(await db.query<{r:{id:string}}>("select public.begin_daily_market_refresh('fixture') r")).rows[0].r;
    await db.query('select public.finish_daily_market_refresh($1,$2,$3)',[failedRun.id,'[]','[{"instrument":"VOD.L","reason":"fixture"}]']);
    await db.query('select portfolio_private.market_watchdog()');
    assert.equal((await db.query<{v:boolean}>("select exists(select 1 from portfolio_private.market_alerts where resolved_at is null) v")).rows[0].v,true);
    console.log('Architecture: minor units, typed instruments, dated FX, retries/cancellation, editorial ownership/MFA/revocation, public reads, invitation recovery, patches/idempotency/conflicts, separate captures and worker health passed.');
} finally {await db.close();}
