import assert from 'node:assert/strict';
import {PortfolioCloudStorage,captureLocalPortfolio,canonicalPortfolio,portfolioStorage} from '../src/services/portfolioCloudStorage';
import type {CloudData,CloudRecord} from '../src/services/portfolioCloudStorage';

const local=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>local.get(key)??null,setItem:(key:string,value:string)=>local.set(key,value),removeItem:(key:string)=>local.delete(key)}});
const network={onLine:true};Object.defineProperty(globalThis,'navigator',{value:network,configurable:true});
const position={id:'test',symbol:'TEST',name:'Synthetic',type:'stock',quantity:1,purchasePrice:10,purchaseDate:'2026-01-01',currency:'EUR',currentPrice:12};
const portfolio=JSON.stringify({version:1,assets:[position],transactions:[]});
local.set('freewallet_portfolio_v1',portfolio);local.set('freewallet_finnhub_key','private-device-only');local.set('freewallet-news-auth','private-session');
const backup=captureLocalPortfolio();assert.equal('freewallet_finnhub_key' in backup,false);assert.equal('freewallet-news-auth' in backup,false);
assert.equal(JSON.parse(backup.freewallet_portfolio_v1).assets[0].currentPrice,undefined);
const storage=new PortfolioCloudStorage();
assert.equal(storage.getItem('freewallet_portfolio_v1'),portfolio);
const saved: {id:string;revision:number;data:CloudData}[]=[];
storage.select('A',async(revision,id,data)=>{saved.push({id,revision,data});return {revision:revision+1,data};});
assert.equal(storage.getItem('freewallet_portfolio_v1'),null,'Account never falls back to guest data');
assert.throws(()=>storage.setItem('freewallet_history','[]'));
storage.hydrate({revision:1,data:backup});
storage.setItem('freewallet_theme_mode','light');await storage.flush();
assert.equal(storage.getSnapshot().status,'synced');assert.equal(saved.length,1);
await storage.flush();assert.equal(saved.length,1,'No-op must not call the backend');
storage.setItem('freewallet_portfolio_v1',portfolio);await storage.flush();assert.equal(saved.length,1,'Quotes must not trigger a state write');
assert.equal(JSON.parse(storage.getItem('freewallet_portfolio_v1')!).assets[0].currentPrice,12);
storage.setItem('freewallet_theme_mode','dark');await storage.flush();
assert.equal(JSON.parse(storage.getItem('freewallet_portfolio_v1')!).assets[0].currentPrice,12,'Acknowledgement retains quote cache');
network.onLine=false;assert.throws(()=>storage.setItem('freewallet_theme_mode','system'));network.onLine=true;
let attempts=0;const ids:string[]=[];
storage.select('A',async(revision,id,data)=>{ids.push(id);if(attempts++===0)throw new Error('Network lost after sending');return {revision:revision+1,data};});
storage.hydrate({revision:2,data:backup});storage.setItem('freewallet_theme_mode','dark');
await assert.rejects(storage.flush());assert.equal(storage.getSnapshot().status,'error');
assert.equal(storage.exportData().freewallet_theme_mode,'dark','Pending edits remain exportable');
assert.throws(()=>storage.setItem('freewallet_theme_mode','system'));
await storage.flush();assert.equal(ids[0],ids[1],'Uncertain retry preserves request identifier');
assert.equal(storage.getSnapshot().status,'synced');
storage.select('A',async()=>{throw {code:'40001'};});storage.hydrate({revision:4,data:backup});
storage.setItem('freewallet_theme_mode','dark');await assert.rejects(storage.flush());
assert.equal(storage.getSnapshot().status,'conflict');await assert.rejects(storage.flush());
assert.equal(storage.exportData().freewallet_theme_mode,'dark');storage.discard();
assert.equal(storage.exportData().freewallet_theme_mode,undefined,'Discard is explicit');
let finish:(record:CloudRecord)=>void=()=>{};
storage.select('A',()=>new Promise(resolve=>{finish=resolve;}));storage.hydrate({revision:1,data:backup});storage.setItem('freewallet_theme_mode','dark');
const inFlight=storage.flush();storage.select('B');storage.hydrate({revision:8,data:{freewallet_portfolio_v1:canonicalPortfolio(JSON.stringify({version:1,assets:[],transactions:[]}))}});
finish({revision:2,data:{...backup,freewallet_theme_mode:'dark'}});await assert.rejects(inFlight);
assert.equal(storage.getSnapshot().userId,'B');assert.equal(storage.currentRevision,8);
assert.equal(JSON.parse(storage.getItem('freewallet_portfolio_v1')!).assets.length,0,'Late A response cannot contaminate B');
assert.equal(storage.recoveredData(),null,'B cannot export A pending edits');
storage.select('A');assert.equal(storage.recoveredData()?.freewallet_theme_mode,'dark','Reauthenticated account can recover an interrupted draft');
storage.select(null);assert.equal(local.get('freewallet_portfolio_v1'),portfolio,'Migration/logout never mutate the local backup');
const {commitPortfolioState}=await import('../src/services/storageService');
let bWrites=0;
portfolioStorage.select('A',async(revision,_id,data)=>({revision:revision+1,data}));
portfolioStorage.hydrate({revision:1,data:backup});
const operation=commitPortfolioState([position],[]);
portfolioStorage.select('B',async(revision,_id,data)=>{bWrites++;return {revision:revision+1,data};});
portfolioStorage.hydrate({revision:1,data:{freewallet_portfolio_v1:JSON.stringify({version:1,assets:[],transactions:[]})}});
await assert.rejects(operation,/sesión ha cambiado/);
assert.equal(bWrites,0,'Account switch during pre-operation flush must not send A positions as B');
assert.equal(JSON.parse(portfolioStorage.getItem('freewallet_portfolio_v1')!).assets.length,0);
portfolioStorage.select(null);
console.log('Sync passed: whitelist, guest isolation, quote-only cache, acknowledgements, offline read-only, exact retry, conflict export/discard and late-session responses.');
