import assert from 'node:assert/strict';
import { assetPrice, assetValue, formatQuantity, convertHistoryToCurrency } from '../src/services/assetValuation';
import { getExposureIdentity, buildConsolidatedPortfolioExposures } from '../src/services/portfolioComposition';
import { calculatePreviousClosePerformance, createQuoteSnapshot, normalizePortfolioTransactions, performanceSeries, selectPortfolioPeriod } from '../src/services/portfolioPerformance';
import { continueWorkbookHistory } from '../src/services/dashboardHistory';
import { buildWorkbookHistory } from '../src/services/portfolioWorkbookHistory';
import type { Asset, HistoricalDataPoint } from '../src/types/types';

// Public regression fixtures are synthetic, never the user's portfolio.
const asset: Asset = { id: 'synthetic', name: 'Synthetic instrument', symbol: 'TEST', type: 'crypto', quantity: .01234567, purchasePrice: 100, currency: 'EUR', purchaseDate: '2026-01-01', currentPrice: 90 };
assert.equal(assetPrice({ ...asset, currentPrice: 0 }), 0);
assert.equal(assetValue({ ...asset, currentPrice: 0 }), 0);
assert.equal(calculatePreviousClosePerformance([{ ...asset, currentPrice: 0, previousClose: 100 }]).returnPercent, -100);
assert.equal(calculatePreviousClosePerformance([{ ...asset, type: 'cash', quantity: 100, currentPrice: undefined }]).returnPercent, 0);
assert.equal(assetPrice({ ...asset, currentPrice: NaN }), 100);
assert.equal(formatQuantity(asset), '0,01234567');
assert.equal(createQuoteSnapshot([asset], [], '2026-09-30T12:00:00Z'), null, 'Opening the page cannot verify old quotes');
assert.equal(createQuoteSnapshot([{ ...asset, lastCheckedAt: '2026-09-30T11:59:00Z' }], [], '2026-09-30T12:00:00Z')?.source, 'quotes-v2');
assert.notEqual(getExposureIdentity('Same name', 'A', 'US0000000001'), getExposureIdentity('Same name', 'B', 'US0000000002'));
assert.equal(getExposureIdentity('First name', 'A', 'US0000000001'), getExposureIdentity('Different name', 'B', 'US0000000001'));
const exposures = buildConsolidatedPortfolioExposures([{ ...asset, type: 'fund', quantity: 1, currentPrice: 100 }], new Map([[asset.id, [{ name: 'Synthetic stock', symbol: 'ABC', isin: 'US0000000001', percentage: 30 }]]]));
assert.equal(exposures.reduce((sum, e) => sum + e.weight, 0), 100);
assert.equal(normalizePortfolioTransactions([asset], [])[0].provenance, 'initial-position');
const history = performanceSeries([{ date: '2026-08-31', value: 1000, invested: 1000 }, { date: '2026-09-01', value: 1020, invested: 1000 }, { date: '2026-09-29', value: 1030, invested: 1000 }], [], [], { maxGapDays: 45 });
const period = selectPortfolioPeriod(history, '1M', Date.parse('2026-09-30T12:00:00Z'));
assert.equal(period.performance.baseDate, '2026-08-31');
assert.equal(period.points[0].date, period.performance.baseDate);
assert.ok(Math.abs(period.performance.returnPercent! - 3) < 1e-8);
const dailyGap = performanceSeries([{ date: '2026-09-01', value: 1000, invested: 1000, cadence: 'daily' }, { date: '2026-09-29', value: 1030, invested: 1000, cadence: 'daily' }], [], [], {maxGapDays: 45});
assert.equal(dailyGap[1].dailyReturn, null);
const candle = (date: string, close: number, currency: string): HistoricalDataPoint => ({ date, close, open: close, high: close, low: close, volume: 0, currency });
const converted = convertHistoryToCurrency([candle('2026-09-02', 100, 'USD'), candle('2026-09-30', 120, 'USD')], [candle('2026-09-01', .9, 'EUR')]);
assert.equal(converted.length, 1);
assert.equal(converted[0].close, 90);
assert.equal(converted[0].currency, 'EUR');
const workbook = buildWorkbookHistory('2026\nMes,Valor Total,Capital Inicial,Capital Aportado\nEne,1000,1000,0\nFeb,1100,1000,0', '');
const isolated = continueWorkbookHistory(workbook, [{ date: '2026-03-01', value: 99999, invested: 1000 }], [], Date.parse('2026-03-02'));
assert.equal(isolated.history.length, workbook.points.length, 'Unlinked workbook cannot adopt another portfolio valuation');
console.log('Dashboard audit regressions passed: valuation, precision, provenance, periods, currencies, identities, daily gaps and workbook scope.');
